AllCops:
  Exclude:
    - test/**/*
    - tmp/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/SpaceAroundOperators:
  AllowForAlignment: true

# This gem needs to load YAML files that contain Symbol keys.
Security/YAMLLoad:
  Enabled: false
