AllCops:
  Exclude:
    - test/**/*
    - tmp/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

MethodLength:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/SpaceAroundOperators:
  AllowForAlignment: true

# This gem needs to load YAML files that contain Symbol keys.
Security/YAMLLoad:
  Enabled: false
